USE [master]
GO
/****** Object:  Database [Fly_Turismo]    Script Date: 14/12/2021 23:43:51 ******/
CREATE DATABASE [Fly_Turismo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Fly_Turismo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Fly_Turismo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Fly_Turismo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Fly_Turismo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Fly_Turismo] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Fly_Turismo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Fly_Turismo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Fly_Turismo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Fly_Turismo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Fly_Turismo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Fly_Turismo] SET ARITHABORT OFF 
GO
ALTER DATABASE [Fly_Turismo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Fly_Turismo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Fly_Turismo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Fly_Turismo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Fly_Turismo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Fly_Turismo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Fly_Turismo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Fly_Turismo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Fly_Turismo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Fly_Turismo] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Fly_Turismo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Fly_Turismo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Fly_Turismo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Fly_Turismo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Fly_Turismo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Fly_Turismo] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Fly_Turismo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Fly_Turismo] SET RECOVERY FULL 
GO
ALTER DATABASE [Fly_Turismo] SET  MULTI_USER 
GO
ALTER DATABASE [Fly_Turismo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Fly_Turismo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Fly_Turismo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Fly_Turismo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Fly_Turismo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Fly_Turismo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Fly_Turismo', N'ON'
GO
ALTER DATABASE [Fly_Turismo] SET QUERY_STORE = OFF
GO
USE [Fly_Turismo]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 14/12/2021 23:43:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clientes]    Script Date: 14/12/2021 23:43:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[Id_Cliente] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](max) NOT NULL,
	[Idade] [int] NOT NULL,
	[CPF] [int] NOT NULL,
	[Telefone] [nvarchar](max) NOT NULL,
	[Endereco] [nvarchar](max) NOT NULL,
	[DestinoId_destino] [int] NOT NULL,
	[HospedagemId_hospedagem] [int] NOT NULL,
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 
(
	[Id_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Destinos]    Script Date: 14/12/2021 23:43:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Destinos](
	[Id_Destino] [int] IDENTITY(1,1) NOT NULL,
	[Cidade] [nvarchar](max) NOT NULL,
	[Pais] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Destinos] PRIMARY KEY CLUSTERED 
(
	[Id_Destino] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Hospedagens]    Script Date: 14/12/2021 23:43:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hospedagens](
	[Id_Hospedagem] [int] IDENTITY(1,1) NOT NULL,
	[Tipo_Hospedagem] [nvarchar](max) NOT NULL,
	[Data_Entrada] [nvarchar](max) NOT NULL,
	[Data_Saida] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Hospedagens] PRIMARY KEY CLUSTERED 
(
	[Id_Hospedagem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Clientes_DestinoId_destino]    Script Date: 14/12/2021 23:43:51 ******/
CREATE NONCLUSTERED INDEX [IX_Clientes_DestinoId_destino] ON [dbo].[Clientes]
(
	[DestinoId_destino] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Clientes_HospedagemId_hospedagem]    Script Date: 14/12/2021 23:43:51 ******/
CREATE NONCLUSTERED INDEX [IX_Clientes_HospedagemId_hospedagem] ON [dbo].[Clientes]
(
	[HospedagemId_hospedagem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Clientes]  WITH CHECK ADD  CONSTRAINT [FK_Clientes_Destinos_DestinoId_destino] FOREIGN KEY([DestinoId_destino])
REFERENCES [dbo].[Destinos] ([Id_Destino])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Clientes] CHECK CONSTRAINT [FK_Clientes_Destinos_DestinoId_destino]
GO
ALTER TABLE [dbo].[Clientes]  WITH CHECK ADD  CONSTRAINT [FK_Clientes_Hospedagens_HospedagemId_hospedagem] FOREIGN KEY([HospedagemId_hospedagem])
REFERENCES [dbo].[Hospedagens] ([Id_Hospedagem])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Clientes] CHECK CONSTRAINT [FK_Clientes_Hospedagens_HospedagemId_hospedagem]
GO
USE [master]
GO
ALTER DATABASE [Fly_Turismo] SET  READ_WRITE 
GO
